Repository luxonis/depthai-core, pull requests merged in 2021-05, with the labels that each got.

#126 Update FW with fix for resource allocation when depth is enabled; fix…
  cmake/Depthai/DepthaiDeviceSideConfig.cmake
  examples/src/camera_preview_example.cpp
  examples/src/stereo_example.cpp
  examples/src/system_information_example.cpp
  src/device/Device.cpp
Labels: Gen2

#138 Update FW with fix for random crashes (kernel crash on RPI/jetson)
  cmake/Depthai/DepthaiDeviceSideConfig.cmake
Labels: 2021, Gen2, bug

#135 OV9282: fix over-exposure outdoors, in sunlight
  cmake/Depthai/DepthaiDeviceSideConfig.cmake
  include/depthai/pipeline/node/MonoCamera.hpp
  src/pipeline/node/MonoCamera.cpp
Labels: Gen2, bug

#141 Add object tracker video example
  examples/CMakeLists.txt
  examples/src/object_tracker_video.cpp
  examples/src/stereo_depth_video.cpp
  examples/src/video_mobilenet.cpp
Labels: Gen2, documentation, enhancement
