Repository luxonis/depthai-core, pull requests merged in 2021-06, with the labels that each got.

#143 Added example on how to add a queue callback in cpp
  examples/CMakeLists.txt
  examples/src/queue_add_callback.cpp
Labels: Gen2, enhancement

#152 Synchronize calibration examples w/ python
  examples/src/calibration_flash.cpp
  examples/src/calibration_flash_v5.cpp
  examples/src/calibration_load.cpp
  examples/src/calibration_reader.cpp
Labels: Gen2, enhancement

#156 Fixed Seg Fault in getImuToCameraExtrinsics
  src/device/CalibrationHandler.cpp
Labels: Gen2

#163 Calib fix
  cmake/Depthai/DepthaiDeviceSideConfig.cmake
  src/device/CalibrationHandler.cpp
Labels: 2021, Gen2, bug
